## Lecture 07: Pandas

In [1]:
#!pip install pandas 
# project yêu cầu pandas version 12.3.2?

In [2]:
import numpy as np
import pandas as pd

In [3]:
s1 = pd.Series(range(10,14), index=list("abcd"))
s1

a    10
b    11
c    12
d    13
dtype: int64

In [4]:
s1.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [5]:
s1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [6]:
s1.values

array([10, 11, 12, 13])

In [7]:
s1['a']

np.int64(10)

In [8]:
s1[0]

C:\Users\Admin\AppData\Local\Temp\ipykernel_22372\643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

np.int64(10)

In [9]:
s1.iloc[0]

np.int64(10)

In [10]:
s1.loc['a']

np.int64(10)

In [11]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                    'Florida': 170312, 'New York': 141297,
                    'Pennsylvania': 119280})
pop = pd.Series({'California': 39538223, 'Texas': 29145505,
                    'Florida': 21538187, 'New York': 20201249,
                    'Pennsylvania': 13002700})
data = pd.DataFrame({'area':area, 'pop':pop})

In [12]:
data

                area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvania  119280  13002700

In [13]:
data['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [14]:
data[['pop','area']]

                   pop    area
California    39538223  423967
Texas         29145505  695662
Florida       21538187  170312
New York      20201249  141297
Pennsylvania  13002700  119280

In [15]:
data.iloc[0]

area      423967
pop     39538223
Name: California, dtype: int64

In [16]:
data.loc['Texas']

area      695662
pop     29145505
Name: Texas, dtype: int64

In [17]:
data.iloc[:2,:]

              area       pop
California  423967  39538223
Texas       695662  29145505

In [18]:
data

                area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvania  119280  13002700

In [19]:
data.loc[:'Florida',:]

              area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

In [20]:
rng = np.random.default_rng(42)
ser = pd.Series(rng.integers(0, 10, 4))
df = pd.DataFrame(rng.integers(0, 10, (3, 4)),columns=['A', 'B', 'C', 'D'])
df

   A  B  C  D
0  4  8  0  6
1  2  0  5  9
2  7  7  7  7

In [21]:
ser

0    0
1    7
2    6
3    4
dtype: int64

In [22]:
np.exp(ser)

0       1.000000
1    1096.633158
2     403.428793
3      54.598150
dtype: float64

In [23]:
np.sin(df * np.pi / 4)

              A             B         C         D
0  1.224647e-16 -2.449294e-16  0.000000 -1.000000
1  1.000000e+00  0.000000e+00 -0.707107  0.707107
2 -7.071068e-01 -7.071068e-01 -0.707107 -0.707107

In [24]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967}, name='area')
population = pd.Series({'California': 39538223, 'Texas': 29145505, 'Florida': 21538187}, name='population')
print(population)
print(area)

California    39538223
Texas         29145505
Florida       21538187
Name: population, dtype: int64
Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [25]:
 population/area

Alaska              NaN
California    93.257784
Florida             NaN
Texas         41.896072
dtype: float64